# Generated by Django 4.1.5 on 2023-02-13 13:42

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidade_uf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('birthday', models.DateField(verbose_name='Aniversário')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Sobre')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients_photos', verbose_name='Foto')),
                ('cpf', cpf_field.models.CPFField(blank=True, max_length=14, null=True, verbose_name='cpf')),
                ('rg', models.CharField(blank=True, max_length=14, null=True, verbose_name='RG')),
                ('sexo', models.CharField(choices=[['F', 'Feminino'], ['M', 'Masculino'], ['N', 'Nenhuma das opções']], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cliente.person')),
                ('telefone', models.CharField(blank=True, max_length=31, null=True, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=50, verbose_name='End')),
                ('numero', models.CharField(max_length=5, verbose_name='nº')),
                ('bairro', models.CharField(max_length=20, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cidade_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade_uf.cidadeuf', verbose_name='Cidade/UF')),
            ],
            bases=('cliente.person',),
        ),
    ]
