# Generated by Django 4.1.5 on 2023-02-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'CIDADES',
                'ordering': ['cidade'],
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'REGIÕES',
            },
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40, verbose_name='Unidade Federativa')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla Estado')),
                ('regiao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade_uf.regiao', verbose_name='Região')),
            ],
            options={
                'verbose_name_plural': 'TABELA ESTADOS',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='CidadeUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade_uf.cidades')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade_uf.unidadefederativa')),
            ],
            options={
                'verbose_name_plural': 'CIDADES/ESTADO',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Capitais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade_uf.cidadeuf')),
            ],
            options={
                'verbose_name_plural': 'CAPITAIS',
                'ordering': ['cidade'],
            },
        ),
    ]
